CA_Django_connector/urls.py
from django.urls import path

from .views import (FileDeleteView, Home, ProjectAutocomplete, ProjectCreateView, ProjectFilesView, ProjectUpdateView, ProjectTypeAutocomplete, ProjectParticipantAutocomplete,
                    ProjectParticipantCreateView, PlaceCreateView, ResourceCreateView, RightsBrowse,
                    ThemeCreateView, KeywordCreateView, ProjectDetailView,
                    PlaceAutocomplete, ThemesAutocomplete, KeywordsAutocomplete, ResourceAutocomplete,
                    ProjectDashboardView, RightsAutocomplete, upload_file)

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("Dashboard/projects/", ProjectDashboardView.as_view(), name="project_dashboard"),
    path("Create/participant/", ProjectParticipantCreateView.as_view(), name="create_participant"),
    path("Create/project/", ProjectCreateView.as_view(), name="create_project"),
    path("Create/place/", PlaceCreateView.as_view(), name="create_place"),
    path("Create/resource/", ResourceCreateView.as_view(), name="create_resource"),
    path("Create/theme/", ThemeCreateView.as_view(), name="create_theme"),
    path("Create/keyword/", KeywordCreateView.as_view(), name="create_keyword"),
    path("Update/project/<int:pk>/", ProjectUpdateView.as_view(), name="update_project"),
    path("Detail/project/<int:pk>/", ProjectDetailView.as_view(), name="project_detail"),
    path("Browse/rights/", RightsBrowse.as_view(), name="rights_browse"),
    path("typeproject-autocomplete", ProjectTypeAutocomplete.as_view(), name="typeproject-autocomplete"),
    path('projectparticipant-autocomplete', ProjectParticipantAutocomplete.as_view(), name="projectparticipant-autocomplete"),
    path("place-autocomplete", PlaceAutocomplete.as_view(), name="place-autocomplete"),
    path("themes-autocomplete", ThemesAutocomplete.as_view(), name="themes-autocomplete"),
    path("rights-autocomplete", RightsAutocomplete.as_view(), name="rights-autocomplete"),
    path("keywords-autocomplete", KeywordsAutocomplete.as_view(), name="keywords-autocomplete"),
    path("resource-autocomplete", ResourceAutocomplete.as_view(), name='resource-autocomplete'),
    path("upload/", upload_file, name='upload'),
    path('upload/project/<int:pk>/', upload_file, name='upload_with_project'),
    path("Files/project/<int:pk>/", ProjectFilesView.as_view(), name='project_files'),
    path("projects-autocomplete/", ProjectAutocomplete.as_view(), name='projects-autocomplete'),
    path('file/delete/<int:pk>/', FileDeleteView.as_view(), name='file_delete'),
]

filebox/urls.py
from django.urls import path

from .views import Home, upload_file, ProjectAutocomplete
from CA_Django_connector.views import ProjectDashboardView


urlpatterns = [
    path("", Home.as_view(), name="home"),
    path("upload/", upload_file, name='upload'),
    path("projects-autocomplete/", ProjectAutocomplete.as_view(), name='projects-autocomplete')
]

ifcollectors/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("filebox.urls")),
    path("", include("exhibits.urls")),
    path("", include('CA_Django_connector.urls')),
    path("", include("collected.urls")),
    path('users/', include('django.contrib.auth.urls')),
    path("users/", include("authusers.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CA_Django_connector/models.py
import os
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords
from django_ckeditor_5.fields import CKEditor5Field

# Create your models here.

class Place(models.Model):
    
    place_name = models.CharField(max_length=100)
    place_type = models.CharField(max_length=50, null=True)
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    lon = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    
    is_part_of = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='children')
    
    def __str__(self) -> str:
        return f'{self.place_name} ({self.place_type})'


class Languages(models.Model):
    
    language = models.CharField(max_length=100)
    iso_language_name = models.CharField(max_length=100)
    alpha2 = models.CharField(max_length=2)
    alpha3 = models.CharField(max_length=3)

    history = HistoricalRecords()
    
class Themes(models.Model):
    
    theme = models.CharField(max_length=70, unique=True, blank=True)
    description = models.CharField(max_length=200, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        self.theme = self.theme.lower() if self.theme else ''
        if Themes.objects.filter(theme=self.theme).exists():
            raise ValidationError(f"This term '{self.theme}' already exists.")
        super().save(*args, **kwargs)
    
    def __str__(self) -> str:
        return f"{self.theme}"

class Keywords(models.Model):
    
    keyword = models.CharField(max_length=70, unique=True, blank=True)
    description = models.CharField(max_length=200, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        self.keyword = self.keyword.lower() if self.keyword else ''
        if Keywords.objects.filter(keyword=self.keyword).exists():
            raise ValidationError(f"This term '{self.keyword}' already exists.")
        super().save(*args, **kwargs)
    
    def __str__(self) -> str:
        return f"{self.keyword}"

class Rights(models.Model):
    
    license = models.CharField(max_length=100)
    license_abreviation = models.CharField(max_length=20)
    license_expanded = models.CharField(max_length = 600)
    canonical_url = models.URLField(unique=True, null=True)
    icon_url = models.URLField(unique=True, null=True)
    
    def __str__(self) -> str:
        return f"({self.license_abreviation}) {self.license}"

class ExternalResource(models.Model):
    
    type_of_resource = models.CharField(max_length=80,
        choices=(
            ('web', 'Website'),
            ('exh', 'Exhibit'),
            ('pub', 'Publication')
        ), default='web'
    )
    resource_name = models.CharField(max_length=200, unique=True)
    url = models.URLField(unique=True)
    
    def __str__(self) -> str:
        return f"{self.resource_name}"
    
class ProjectTypes(models.Model):
    
    project_type = models.CharField(max_length=200, unique=True)
    type_description = models.CharField(max_length=300, blank=True, null=True)
    
    def __str__(self) -> str:
        return f'{self.project_type}'

class SecondLangDescriptions(models.Model):
    
    project_description = models.TextField(max_length=1000)
    language = models.CharField(max_length=20, null=True, blank=True)

class ProjectParticipant(models.Model):
    
    full_name = models.CharField(max_length=300)
    email = models.EmailField(blank=True, null=True)
    project_role = models.CharField(max_length=200, blank=True)
    
    
    def __str__(self) -> str:
        return f'{self.full_name}'

class Project(models.Model):
    """
    Reduced model for the table ca_collections
    """
    
    project_idno = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=200, unique=True,)
    project_description = CKEditor5Field(max_length=10000, null=True, blank=True, config_name="extends")
    project_description_second = CKEditor5Field(max_length=10000, null=True, blank=True, config_name="extends")
    
    type_of_project = models.ForeignKey(ProjectTypes, on_delete=models.CASCADE)
    
    themes = models.ManyToManyField(Themes, blank=True)
    keywords = models.ManyToManyField(Keywords, blank=True)
    
    users = models.ManyToManyField(User, through='administration.UserProject', blank=True)
    participants = models.ManyToManyField(ProjectParticipant, blank=True, related_name="project_participants")
    country_or_region = models.ManyToManyField(Place, blank=True)
    external_resources = models.ManyToManyField(ExternalResource, blank=True)
    
    ifrepourl =  models.URLField(null=True, blank=True)
    
    thumbnail = models.ImageField(upload_to='thumbnails/', help_text='Share files under 10MB', blank=True, null=True)  
    thumbnail_rights = models.ForeignKey(Rights, on_delete=models.DO_NOTHING, related_name="thumbnail_rights", null=True)
    thumbnail_note = models.CharField(max_length=250, blank=True, null=True)
    
    history = HistoricalRecords()
    
    class Meta:
        permissions = [
            ("edit_project", "Can edit project"),
        ]
    
    def __str__(self) -> str:
        return f'{self.name}'

class UploadFile(models.Model):
    project = models.ForeignKey(Project, related_name='files', on_delete=models.CASCADE)

    def project_idno_file(instance, filename):
        # Prepends the project_idno to the filename
        basename, file_extension = os.path.splitext(filename)
        new_filename = "{project_idno}_{base}{ext}".format(project_idno=instance.project.project_idno, base=basename, ext=file_extension)
        return 'uploads/{0}'.format(new_filename)

    file = models.FileField(upload_to=project_idno_file)
    #thumbnail = models.ImageField(upload_to='thumbnails/', blank=True, null=True)
    
    def __str__(self) -> str:
        return f'{self.file}'

class Records(models.Model):
    """
    Reduced model for ca_objects
    """
    
    record_idno = models.CharField(max_length=100, unique=True)
    collection = models.ManyToManyField(Project)
    preferred_labels = models.CharField(max_length=200)
    langmaterial = models.ManyToManyField(Languages, blank=True)
    themes = models.ManyToManyField(Themes, blank=True)
    places = models.ManyToManyField(Place, blank=True)
    date_creation = models.DateField(blank=True, null=True)
    creator = models.ManyToManyField(User, blank=True, related_name='creators')
    rights_holders = models.ManyToManyField(User, blank=True, related_name='rights_holders')
    license = models.ForeignKey(Rights, on_delete=models.SET_DEFAULT, default=1)
    media = models.ManyToManyField(UploadFile, blank=True)
    
    history = HistoricalRecords()


    

CA_Django_connector/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget
from dal import autocomplete
from .models import (ExternalResource, Keywords, Place, Project, ProjectTypes, ProjectParticipant, Records, Themes,
                     Rights, UploadFile)

class ProjectParticipantForm(forms.ModelForm):
    class Meta:
        model = ProjectParticipant
        fields = ['full_name', 'email', 'project_role']
        
    def __init__(self, *args, **kwargs):
        super(ProjectParticipantForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.fields.TypedChoiceField):
                field.widget.attrs['class'] = 'form-select'
            else:
                field.widget.attrs['class'] = 'form-control'

class ExternalResourceForm(forms.ModelForm):
    class Meta:
        model = ExternalResource
        fields = '__all__'
    
    url = forms.URLField(max_length=100, required=True)
        
    def __init__(self, *args, **kwargs):
        super(ExternalResourceForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ThemeForm(forms.ModelForm):
    class Meta:
        model = Themes
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super(ThemeForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class KeywordForm(forms.ModelForm):
    class Meta:
        model = Keywords
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super(KeywordForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = '__all__'

    lat = forms.DecimalField(max_digits=9, decimal_places=6, required=False)
    lon = forms.DecimalField(max_digits=9, decimal_places=6, required=False)
    
    
    def clean(self):
        cleaned_data = super().clean()
        lat = cleaned_data.get('lat')
        lon = cleaned_data.get('lon')
        
        if (lat is not None and lon is None) or (lat is None and lon is not None):
            raise forms.ValidationError("Both latitude and longitude are required together.")

        return cleaned_data
    
    def __init__(self, *args, **kwargs):
        super(PlaceForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    
class ProjectForm(forms.ModelForm):
    
    class Meta:
        model = Project
        fields = '__all__'
        
    
    name = forms.CharField(max_length=200, required=True)
    #project_description = forms.CharField(widget=CKEditor5Widget(config_name='extends'), required=False)
    #project_description_second = forms.CharField(widget=CKEditor5Widget(config_name='extends'), required=False)
    type_of_project = forms.ModelChoiceField(
        queryset=ProjectTypes.objects.all(),
        required=False,
        widget=autocomplete.ModelSelect2(url='typeproject-autocomplete', attrs={'placeholder': 'Select project type'}),
        label='Project Type'
    )
    
    participants = forms.ModelMultipleChoiceField(
        queryset=ProjectParticipant.objects.all(),
        required=True,
        widget=autocomplete.ModelSelect2Multiple(url='projectparticipant-autocomplete', attrs={'placeholder': 'Select or add project leaders'}),
        label='Project Leaders'
    )
    
    country_or_region = forms.ModelMultipleChoiceField(
        queryset=Place.objects.all(),
        required=False,
        widget=autocomplete.ModelSelect2Multiple(url='place-autocomplete', attrs={'placeholder': 'Select place'}),
        label="Place"
    )
    
    external_resources = forms.ModelMultipleChoiceField(
        queryset=ExternalResource.objects.all(),
        required=False,
        widget=autocomplete.ModelSelect2Multiple(url='resource-autocomplete'),
        label="External Resource"
    )
    
    themes = forms.ModelMultipleChoiceField(
        queryset=Themes.objects.all(),
        required=True,
        widget=autocomplete.ModelSelect2Multiple(url='themes-autocomplete', attrs={'placeholder': 'Select general themes'}),
        label="Themes"
    )
    
    keywords = forms.ModelMultipleChoiceField(
        queryset=Keywords.objects.all(),
        required=True,
        widget=autocomplete.ModelSelect2Multiple(url='keywords-autocomplete', attrs={'placeholder': 'Select more specific themes'}),
        label="Keywords"
    )
    
    thumbnail_rights = forms.ModelChoiceField(
        queryset= Rights.objects.all(),
        required=True,
        widget=autocomplete.ModelSelect2(url='rights-autocomplete', attrs={'placeholder': 'Select rights'}),
        label="Rights"
    )
    
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
                
        if self.instance and self.instance.pk:
            self.fields['project_idno'].widget = forms.HiddenInput()
            self.fields['type_of_project'].widget = forms.HiddenInput()
        
        if self.instance.pk:
            self.fields['users'].initial = self.instance.users.all()
            
        self.fields['users'].widget = forms.MultipleHiddenInput()
        
        if self.instance and self.instance.pk and self.instance.thumbnail:
            self.fields['thumbnail'].widget = forms.FileInput()
            self.current_thumbnail_url = self.instance.thumbnail.url
        else:
            self.current_thumbnail_url = None
        
        for field_name, field in self.fields.items():
            if isinstance(field, forms.fields.TypedChoiceField):
                field.widget.attrs['class'] = 'form-select'
            else:
                field.widget.attrs['class'] = 'form-control'
        
        
        self.fields['themes'].widget.attrs = {'data-placeholder': 'Select general keywords', 'class': 'form-select'}
        self.fields['keywords'].widget.attrs = {'data-placeholder': 'Select specific keywords', 'class': 'form-select'}


class UploadForm(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = ['project']
        
    project = forms.ModelChoiceField(
        queryset=Project.objects.all(),
        required=True,
        widget=autocomplete.ModelSelect2(url='projects-autocomplete', attrs={'placeholder': 'Select project'}),
        label='Project Name'
    )


class RecordsForm(forms.ModelForm):
    class Meta:
        model = Records
        fields = '__all__'
        
    

CA_Django_connector/templates/CA_Django_connector/files/project.html
<!-- templates/CA_Django_connector/files/project.html -->
{% extends 'main.html' %}
{% block content %}
{% load i18n %}
{% csrf_token %}

<div class="container py-6">
    <h2 class="mb-3 page-title">{{ project.name }} - Uploaded Files</h2>
    <div class="list-group">
        {% for file in files %}
        <a href="{{ file.file.url }}" class="list-group-item list-group-item-action">
            {{ file.file.name }}
        </a>
        <button type="button" class="btn btn-outline-danger btn-sm" onclick="confirmDelete('{% url 'file_delete' file.pk %}');"><i class="fas fa-trash-alt" aria-label="Delete"></i></button>
        {% empty %}
        <p>No files uploaded for this project.</p>
        {% endfor %}
    </div>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{% url 'project_dashboard' %}" class="btn btn-secondary">Back to Project Dashboard</a>
    </div>
</div>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmationModalLabel">{% trans 'Confirm delete' %}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% trans 'Do you want to delete this?' %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans 'Cancel' %}</button>
                <button type="button" class="btn btn-danger" id="deleteConfirmBtn">{% trans 'Delete' %}</button>
            </div>
        </div>
    </div>
</div>

{{ form.media }}

<script>
    function confirmDelete(deleteURL) {
        $('#deleteConfirmationModal').modal('show');
    
        document.getElementById('deleteConfirmBtn').onclick = function() {
            const csrftoken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
            console.log("csrf_token");
            console.log(csrftoken);
            $.ajax({
                url: deleteURL,
                type: 'POST',
                beforeSend: function(xhr) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                },
                success: function(result) {
                    $('#deleteConfirmationModal').modal('hide');
                    location.reload(); 
                },
                error: function(xhr, status, error) {
                    console.error(error);
                }
            });
        };
    }
</script>

{% endblock content %}

CA_Django_connector/templates/CA_Django_connector/files/upload.html
{% extends 'main.html' %}
{% load django_bootstrap5 django_bootstrap_input_group static %}
{% block content %}
{% load i18n %}
{% csrf_token %}

{% if perms.CA_Django_connector.add_uploadfile %}
<div class="container py-6">
    <div class="row justify-content-center">
        <div class="col-md-12 shadow auth-forms-container">
            <h2 class="mb-3 page-title">Upload Files</h2>
            <form action="{% if project_id %}{% url 'upload_with_project' project_id %}{% else %}{% url 'upload' %}{% endif %}" method="POST" class="dropzone" id="my-awesome-dropzone" enctype="multipart/form-data">
                {% csrf_token %}
                {% include '_form_errors.html' %}
                <div class="mb-3">
                    <label for="{{ form.project.id_for_label }}" class="form-label">{{ form.project.label }}</label>
                    {{ form.project }}
                </div>

                <div class="d-grid gap-2 d-md-flex justify-content-md-end upload-buttons">
                    <a href="{% if next_url %}{{ next_url }}{% else %}{% url 'project_dashboard' %}{% endif %}" class="btn btn-secondary" id="cancelButton">Cancel</a>
                    <button type="submit" class="btn btn-primary" id="submit-all">Submit</button>
                </div>
            </form>
            <div>
                <p>Each file must be no larger than 2 GB. You can upload up to 50 files at a time.</p>
            </div>
        </div>
        
    </div>
</div>

    {% include '_cancel_warning.html' %}

    {{ form.media }}

    <script>
        var mediatypes = 'image/jpg, image/jpeg, image/png, image/tiff, image/gif, image/bmp, image/webp, video/mp4, video/webm, video/ogg, video/quicktime, audio/mpeg, audio/mp3, audio/ogg, audio/wav, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation, text/plain, text/csv, text/xml, model/gltf-binary, application/zip';

        Dropzone.options.myAwesomeDropzone = {
            paramName: "file",
            autoProcessQueue: false,
            uploadMultiple: true,
            parallelUploads: 10,
            maxFiles: 50,
            maxFilesize: 2000,
            //acceptedFiles: mediatypes,
            init: function() {
                console.log("Dropzone initialized.");
                var myDropzone = this;

                // Log the added file event
                myDropzone.on("addedfile", function(file) {
                    console.log("File added: ", file.name);
                });

                document.querySelector("#submit-all").addEventListener("click", function(e) {
                    e.preventDefault();
                    e.stopPropagation();
                    console.log("Submit button clicked.");
                    if (myDropzone.getQueuedFiles().length > 0) {
                        console.log("Processing queue.");
                        myDropzone.processQueue();
                    } else {
                        console.log("No files in queue.");
                        document.querySelector("#my-awesome-dropzone").submit();
                    }
                });

                myDropzone.on("sendingmultiple", function(file, xhr, formData) {
                    console.log("Sending files.");
                    formData.append("project", document.querySelector("#id_project").value);
                    console.log("Project added to formData: ", document.querySelector("#id_project").value);
                });

                myDropzone.on("successmultiple", function(files, response) {
                    console.log("Files successfully uploaded.");
                    var projectId = "{{ project_id|escapejs }}";
                    if (projectId) {
                        window.location.href = `{% url 'project_detail' project_id %}`;
                    } else {
                        window.location.href = "{% url 'project_dashboard' %}";
                    }
                });

                myDropzone.on("errormultiple", function(files, response) {
                    console.log("Error uploading files: ", response);
                    alert(response.error);
                });

                myDropzone.on("queuecomplete", function() {
                    console.log("All files have been uploaded.");
                    var projectId = "{{ project_id|escapejs }}";
                    if (projectId) {
                        window.location.href = `{% url 'project_detail' project_id %}`;
                    } else {
                        window.location.href = "{% url 'project_dashboard' %}";
                    }
                });
            }
        };
    </script>
{% else %}
<h1>You have no access to this resource.</h1>
{% endif %}
{% endblock content %}